### ISSUE TITLE
All exceptions are shown to the user

### ISSUE THREAD

**Issue by DarkAnHell** [DarkAnHell/practica-final-verificacion#17]
We should add try-execpt blocks (in parse_text) to show a correct error message to the user.

**Comment by jimen0** [comment]
[Referenced file](https://github.com/DarkAnHell/practica-final-verificacion/blob/dev/app/views.py#L8)

**Comment by jimen0** [comment]
Closing this. When lettuce tests are added, `dev-frontend` will be merged.
