### ISSUE TITLE
No check for database connectivity + connection exceptions

### ISSUE THREAD

**Issue by DarkAnHell** [DarkAnHell/practica-final-verificacion#19]
There is no check to see if we are connected to the MongoDB.
[Calling MongoClient()](https://github.com/DarkAnHell/practica-final-verificacion/blob/dev-frontend/app/views.py#L26) does not assure a connection, and thus later on we can run into connection timeouts.

We should add checks either at DB creation, at the back end (parse_text) at db connection, or in all db functions. Or all of them.

**Comment by jimen0** [comment]
Resolved in #23
